use content type charset to decode IACR response
(also, try iso8859-1 if standard decoding doesn't work)

iacr appears to return bibtex data in iso8859-1 format, which makes
python choke here:

0 dkg@alice:~$ xapers add --source=cryptoeprint:2015/659
Retrieving bibtex...Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/dist-packages/xapers/__main__.py", line 192, in <module>
    docid = cli.add(db, query, infile=infile, sid=sid, tags=tags, prompt=prompt)
  File "/usr/lib/python2.7/dist-packages/xapers/cli.py", line 226, in add
    bibtex = source.fetch_bibtex()
  File "/usr/lib/python2.7/dist-packages/xapers/source.py", line 128, in fetch_bibtex
    return super(SourceItem, self).fetch_bibtex(self.id)
  File "/usr/lib/python2.7/dist-packages/xapers/source.py", line 83, in fetch_bibtex
    return self.module.fetch_bibtex(id)
  File "/usr/lib/python2.7/dist-packages/xapers/sources/cryptoeprint.py", line 50, in fetch_bibtex
    return unicode(p.data)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 67: ordinal not in range(128)
1 dkg@alice:~$

You can see this also by looking at the data returned here:

https://eprint.iacr.org/eprint-bin/cite.pl?entry=2015/659